### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by mnm1992** [escaladesports/amazon-reviews-crawler#5]
NPM install fails with:
npm ERR! code 1
npm ERR! Command failed: /usr/local/bin/git checkout 0.1.3
npm ERR! error: pathspec '0.1.3' did not match any file(s) known to git.
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/310189953/.npm/_logs/2017-08-25T12_32_32_881Z-debug.log

**Comment by kennedyrose** [comment]
Fixed now. Thanks for letting me know!

**Comment by mnm1992** [comment]
Sorry but that didn't fix it for me. I am now getting:
> electron@1.7.5 postinstall /Users/310189953/Projects/Hobby projects/review-fetcher/node_modules/electron
> node install.js

module.js:491
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/310189953/Projects/Hobby projects/review-fetcher/node_modules/rimraf/rimraf.js:7:12)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
npm WARN review-fetcher@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/310189953/.npm/_logs/2017-08-25T12_52_22_054Z-debug.log

**Comment by mnm1992** [comment]
The command I use is npm install amazon-reviews-crawler --save btw

**Comment by kennedyrose** [comment]
Strange, I'm running the exact same OS and it doesn't seem to be having a problem. If I had to guess, it might be your Node version. Can you try updating and seeing if it's still a problem?

https://github.com/electron-userland/electron-prebuilt/issues/125

**Comment by mnm1992** [comment]
v8.4.0 node
5.3.0 npm
These are latest greatest, so I assume they are ok. 
But I fixed the issue by manually installing glob and minimatch.
